### ISSUE TITLE
waiterMap should use WeakMap instead of plain object

### ISSUE THREAD

**Issue by ghost** [wmzy/promise-pending-lock#2]
Consider this code snippet:

```javascript
const promisePendingLock = require("promisePendingLock").deafult;

// Simply, delay(x) returns a promise resolves in x ms.
const delay = require("delay");

// Simulate an async task resolves in 200 ms.
const work = promisePendingLock(async (data) => {
  await delay(200);
  console.info(`${Date.now() % 1000} ${data}`);
  return data;
});

(async () => {
  work(A);
  await delay(100);
  work(B);
})();
```

If `A` isn't same as `B`, the second log message should appear after 100 ms since the first one appears.

I noticed this line: ([Line 13](https://github.com/wmzy/promise-pending-lock/blob/21f39a3/promise-pending-lock.js#L13))

```javascript
  const waiterMap = {};
```

Using plain object for `waiterMap` works for most values, but there are plenty edge cases, In following table, `A` and `B` is different, but they are treated as same value.

| `A`                 | `B`        |
|:--------------------|:---------- |
| `"1"`               | `1`        |
| `"1"`               | `[1]`      |
| `"1,2"`             | `[1, 2]`   |
| `"[object Object]"` | `{ a: 1 }` |
| `{ a: 1 }`          | `{ b: 2 }` |

etc.

`{ a: 1 }` and `{ b: 2 }` are treated as same, it's pretty confusing. (both of them are converted to `"[object Object]"` implicitly via [Line 17](https://github.com/wmzy/promise-pending-lock/blob/21f39a3/promise-pending-lock.js#L17)).

```javascript
      waiterMap[pk] = [];
```

There's another worse problem: if calls `work("constructor")`, it would throw `TypeError: waiterMap[pk].push is not a function`. (`"constructor"` is a property of `{}` naturally, so the if statement in [Line 16](https://github.com/wmzy/promise-pending-lock/blob/21f39a3/promise-pending-lock.js#L16) will be skipped.)

```javascript
    if (!waiterMap[pk]) {
```

---

Suggestion:

Use [`WeakMap`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) for `waiterMap`.

But there would be another problem: calling `work()` with same params makes `params` in [Line 14](https://github.com/wmzy/promise-pending-lock/blob/21f39a3/promise-pending-lock.js#L14) different everytime.

```javascript
  return (...params) => {
```

So it's a good idea to use [package `object-hash`](http://npmjs.com/package/object-hash) as default `hashParams` option in [Line 10](https://github.com/wmzy/promise-pending-lock/blob/21f39a3/promise-pending-lock.js#L10).

```javascript
  hashParams = identity,
```

**Comment by wmzy** [comment]
Thanks for your suggestion. 
But `object-hash` is too heavy and could not cover all cases, so that I do not want to make choices for users.
There is no a good `hashParams`, so I use the simplest as placeholder.

`WeakMap` is not proper to use here.Maybe what you mean is `Map`.The problem is apparently.

The "constructor" problem is a bug.I will fix it.
